name: Commit-based Code Scanner

on:
  pull_request:
    branches:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Get path at commit
        id: commit-path
        run: |
          COMMIT_PATH=$(git rev-parse --show-toplevel)
          echo "::set-output name=path::$COMMIT_PATH"

      - name: Log current path and commit ID
        run: |
          echo "Current Path: ${{ steps.commit-path.outputs.path }}"
          echo "Commit ID: ${{ github.event.pull_request.head.sha }}"

      - name: Get repository URL
        id: repo-url
        run: |
          echo "::set-output name=url::$(git remote get-url origin)"

      - name: Running Code scanner
        id: code-scanner
        run: |
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          REPO_URL=${{ steps.repo-url.outputs.url }}
          docker pull rohitcoder/hela
          CONTAINER_ID=$(docker run \
            -d \
            rohitcoder/hela \
            --code-path $REPO_URL \
            --sast --sca --secret  \
            --verbose)
          echo "::set-output name=container-id::$CONTAINER_ID"
          docker wait $CONTAINER_ID

      - name: Copy SARIF report to workspace
        run: |
          CONTAINER_ID=${{ steps.code-scanner.outputs.container-id }}
          docker cp "${CONTAINER_ID}:/tmp/sarif_report.json" "${{ steps.commit-path.outputs.path }}/sarif_report.json"

      - name: Import scan results into DefectDojo
        id: import-scan-results-into-defectdojo
        uses: portswigger-cloud/defectdojo-github-action@v1
        with:
          defectdojo-url: http://65.0.93.107:8080
          defectdojo-username: rohitcoder
          defectdojo-password: rohit@123
          defectdojo-product-type: Insurance AppSec
          defectdojo-product: Insurance AppSec
          defectdojo-environment-type: Production
          defectdojo-scan-type: SARIF
          defectdojo-engagement-name: Hela Scan
          scan-results-file-name: "${{ steps.commit-path.outputs.path }}/sarif_report.json"
